server:
  port: 6789
application:
  payment:
    initial-balance: 1500

springdoc:
  swagger-ui:
    enable: true
    path: /swagger-ui-custom.html
    tryItOutEnabled: true
    persistAuthorization: true


spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/shop
