server:
  port: 9093
payment-service:
  base-url: http://localhost:6789
shop-service:
  base-url: http://localhost:9093/product

spring:
  application:
    name: shop
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/mine
    username: postgres
    password: postgres
    initialization-mode: always
    schema: classpath:schema.sql
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          keycloak-user:
            authorization-grant-type: authorization_code
            provider: keycloak
            client-id: shop-application
            client-secret: UG1PVeAO7mi2oXVdxIZWcSDMkhfa2V73
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: openid, profile, roles
          keycloak-payment-service:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: shop-application
            client-secret: UG1PVeAO7mi2oXVdxIZWcSDMkhfa2V73
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/shop
            user-name-attribute: preferred_username
