CREATE SCHEMA IF NOT EXISTS store;
SET search_path TO store;

CREATE TABLE IF NOT EXISTS store.products (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    price int4,
    description text,
    title varchar(255)
);

CREATE TABLE IF NOT EXISTS store.images (
    id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	product_id int8 REFERENCES store.products ON DELETE CASCADE,
	image_name varchar(255),
	image bytea
);

CREATE TABLE IF NOT EXISTS store.orders (
	id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	username varchar(255)
);

CREATE TABLE IF NOT EXISTS store.items (
	id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	price int4,
	quantity int4,
	order_id int8 REFERENCES store.orders ON DELETE CASCADE,
	product_id int8 REFERENCES store.products ON DELETE RESTRICT
);